include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset
