include:
  - board: xiao_ble//zmk
    shield: totem_left
  - board: xiao_ble//zmk
    shield: totem_right
  - board: xiao_ble//zmk
    shield: totem_dongle prospector_adapter
  - board: xiao_ble//zmk
    shield: settings_reset
